name: rigsnvapi

on:
    push:
      paths:
        - 'server/**'
env:
  AZURE_WEBAPP_NAME: rigsnvapi
  AZURE_WEBAPP_PACKAGE_PATH: './server'
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:  
    - uses: actions/checkout@v4
    - name: Set up Python 3.x
      uses: actions/setup-python@v4
      with:
        python-version: 3.x
    - name: Install dependencies
      run: |
        ls
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      working-directory: 'server'
    - name: Verify environment variables
      run: |
        echo "App Name: $AZURE_WEBAPP_NAME"
        echo "Resource Group: rigsnv_rg_3932"
        echo "Package Path: $AZURE_WEBAPP_PACKAGE_PATH"
    - name: Verify publish profile
      run: |
        echo "${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_RIGSNVAPI }}" | head -n 5
        echo "Publish profile loaded successfully."
    - name: Building web app
      uses: azure/appservice-build@v3
      with:
        source-directory: 'server'
    - name: Deploy web App using GH Action azure/webapps-deploy
      uses: azure/webapps-deploy@v3
      with:
        app-name: rigsnvapi
        resource-group-name: rigsnv_rg_3932
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_RIGSNVAPI }}
        package: 'server'
        slot-name: production


