name: rigsnvapi

on:
    push:
      paths:
        - 'server/**'
env:
  AZURE_WEBAPP_NAME: rigsnvapi # Set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: './server' # Set this to the path to your web app project, defaults to the repository root
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:  
    - uses: actions/checkout@v4
    - name: Set up Python 3.x
      uses: actions/setup-python@v4
      with:
        python-version: 3.x
    - name: Install dependencies
      run: |
        ls
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      working-directory: 'server' # Correct relative path
    - name: Building web app
      uses: azure/appservice-build@v2
      with:
        package: 'server' # Explicitly specify the source directory for the build
    - name: Deploy web App using GH Action azure/webapps-deploy
      uses: azure/webapps-deploy@v3
      with:
        app-name: rigsnvapi
        resource-group-name: rigsnv_rg_3932
        # Suppress warning: This secret is securely managed by GitHub Actions.
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_RIGSNVAPI }}
        package: 'server'        

