name: rigsnvapi

on:
    push:
      paths:
        - 'server/**'
env:
  AZURE_WEBAPP_NAME: rigsnvapi # Set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: './server' # Explicitly set the path to the server directory
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:  
    - uses: actions/checkout@v4
    - name: Set up Python 3.x
      uses: actions/setup-python@v4
      with:
        python-version: 3.x
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ./requirements.txt
      working-directory: './server' # Ensure dependencies are installed from the server directory
    - name: Building web app
      uses: azure/appservice-build@v2
    - name: Deploy web App using GH Action azure/webapps-deploy
      uses: azure/webapps-deploy@v3
      with:
        app-name: rigsnvapi
        resource-group-name: rigsnv_rg_3932
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_RIGSNVAPI }}
        package: './server' # Ensure the server directory is deployed
